"""base 2]3 migration

Revision ID: 2f417399f993
Revises: c638cf367432
Create Date: 2023-04-20 00:50:05.092307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f417399f993'
down_revision = 'c638cf367432'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
