"""changed

Revision ID: b5c8ef22135c
Revises: 1981f4f02efc
Create Date: 2023-05-04 14:15:37.078442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c8ef22135c'
down_revision = '1981f4f02efc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('song_uri', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'song_uri')
    # ### end Alembic commands ###
